---
# Per environment values which override defaults in hmpps-manage-assess-risks-and-needs/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    enabled: false
    host: manage-assess-risks-and-needs-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-assess-risks-and-needs-dev.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  enabled: false
